### ISSUE TITLE
Exception when clicking save

### ISSUE THREAD

**Issue by trumad** [emiyl/PWAATeditor#4]
Hey, thanks for making this

Firstly, here's what I see when I open a savefile:

<img width="848" alt="image" src="https://github.com/user-attachments/assets/991cf143-9dc8-4dfd-8cea-868b7878f1c6">

It looks like maybe there are meant to be comboboxes etc? And I also can't see an option to unlock the save file anywhere?

Finally, when I click the save button on the bottom left, I get this error:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\USERNAME\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\USERNAME\Documents\aceAttorneySaveEditor.py", line 489, in saveChanges
    if self.comboBoxes[element].get() == self.textList[element][setting]:
IndexError: list index out of range`

I'm running the script via Thonny, using "run as administrator" in Windows. I tried opening both gear_sys.dat and gear_game20.dat, closing down the script before each try. I also tried with a raw systemdata file created by the game after it detected that my save file was corrupt.

Please let me know if I'm doing anything wrong. Thanks again for making this!

**Comment by trumad** [comment]
Haa, I'm an idiot. It's early in the morning, and I hadn't spotted that this is not a save file editor for The Great Ace Attorney Chronicles lol. Sorrrrry
